# Generated by Django 4.2 on 2023-05-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=100)),
                ("seller_name", models.CharField(max_length=100)),
                ("seller_phone", models.CharField(max_length=20)),
                ("store_address", models.CharField(max_length=200)),
                ("username_email", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=100)),
                ("store_image", models.ImageField(upload_to="images/")),
                ("qr_code", models.ImageField(upload_to="images/"))
                
            ],
        ),
    ]
