# Generated by Django 3.1.14 on 2023-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='qr_image',
            field=models.ImageField(upload_to='uploads/sellers/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_image',
            field=models.ImageField(upload_to='uploads/sellers/'),
        ),
    ]
