# Generated by Django 4.1.6 on 2023-05-10 07:15

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_alter_customer_id_alter_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(upload_to='uploads/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ImageField(upload_to='uploads/payment/')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('store_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('opening_time', models.TimeField(default=datetime.datetime(2023, 5, 10, 9, 0, 0, 950829, tzinfo=datetime.timezone.utc))),
                ('closing_time', models.TimeField(default=datetime.datetime(2023, 5, 10, 22, 0, 0, 950829, tzinfo=datetime.timezone.utc))),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '0xxxxxxxxx' or '+66xxxxxxxxx'", regex='^(\\+66|0)\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default='', max_length=250)),
                ('store_image', models.ImageField(upload_to='uploads/seller_data/')),
                ('qr_image', models.ImageField(upload_to='uploads/seller_data/')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('stockqty', models.IntegerField(default=999)),
                ('likes_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller')),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('payment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seller.products')),
            ],
        ),
    ]
