# Generated by Django 3.1.14 on 2023-05-08 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.payment'),
            preserve_default=False,
        ),
    ]
