# Generated by Django 4.1.6 on 2023-05-10 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 10, 22, 0, 0, 252605, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 10, 9, 0, 0, 252605, tzinfo=datetime.timezone.utc)),
        ),
    ]
