# Generated by Django 4.2 on 2023-05-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_alter_category_id_alter_orderitem_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="payment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="seller.payment",
            ),
        ),
    ]
