# Generated by Django 4.1.6 on 2023-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_store_name_alter_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='qr_image',
            field=models.ImageField(upload_to='uploads/seller_data/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_image',
            field=models.ImageField(upload_to='uploads/seller_data/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
