# Generated by Django 4.1.6 on 2023-05-06 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0004_alter_seller_qr_image_alter_seller_store_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
