# Generated by Django 4.1.6 on 2023-05-09 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_seller_closing_time_seller_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 9, 22, 0, 0, 535496, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 9, 9, 0, 0, 535496, tzinfo=datetime.timezone.utc)),
        ),
    ]
