# Generated by Django 4.1.6 on 2023-05-06 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0006_category_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vendor',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='seller',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
