# Generated by Django 4.1.6 on 2023-05-09 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_products_likes_count_alter_seller_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 9, 22, 0, 0, 181541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='opening_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 9, 9, 0, 0, 181541, tzinfo=datetime.timezone.utc)),
        ),
    ]
