# Generated by Django 3.1.14 on 2023-05-04 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '0xxxxxxxxx' or '+66xxxxxxxxx'", regex='^(\\+66|0)\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default='', max_length=250)),
                ('store_image', models.ImageField(upload_to='uploads/seller/')),
                ('qr_image', models.ImageField(upload_to='uploads/seller/')),
            ],
        ),
    ]
