# Generated by Django 3.1.7 on 2023-05-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_store_name_alter_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='qr_image',
            field=models.ImageField(upload_to='uploads/seller_data/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_image',
            field=models.ImageField(upload_to='uploads/seller_data/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.category')),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
    ]
