# Generated by Django 3.1.7 on 2023-05-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_remove_seller_shop_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='ordering',
        ),
    ]
