# Generated by Django 3.1.7 on 2023-05-05 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0007_auto_20230505_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='created_by',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='auth.user'),
            preserve_default=False,
        ),
    ]
