# Generated by Django 4.1.6 on 2023-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.CharField(default='', max_length=250),
        ),
    ]
