# Generated by Django 4.1.6 on 2023-05-05 17:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_id_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('store_name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '0xxxxxxxxx' or '+66xxxxxxxxx'", regex='^(\\+66|0)\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(default='', max_length=250)),
                ('store_image', models.ImageField(upload_to='uploads/store_data/')),
                ('qr_image', models.ImageField(upload_to='uploads/store_data/')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
