# Generated by Django 4.1.6 on 2023-05-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_store_alter_products_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='password',
        ),
    ]
