# Generated by Django 4.1.6 on 2023-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_store_first_name_remove_store_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/categories/'),
            preserve_default=False,
        ),
    ]
