# Generated by Django 4.1.6 on 2023-05-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='cat_image',
        ),
    ]
