# Generated by Django 4.2 on 2023-04-21 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(
                db_column="telephone_number",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format '0xxxxxxxxx' or '+66xxxxxxxxx'",
                        regex="^(\\+66|0)\\d{9}$",
                    )
                ],
            ),
        ),
    ]
