# Generated by Django 4.2 on 2023-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_buyer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last Name"),
        ),
    ]
