# Generated by Django 4.2 on 2023-04-21 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_buyer_first_name_alter_buyer_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format '0xxxxxxxxx' or '+66xxxxxxxxx'",
                        regex="^(\\+66|0)\\d{9}$",
                    )
                ],
            ),
        ),
    ]
