# Generated by Django 4.2 on 2023-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_product_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(max_length=999, null=True),
        ),
    ]
