# Generated by Django 4.2 on 2023-04-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_product_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
