# Generated by Django 4.2 on 2023-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_product_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="DEFAULT VALUE", max_length=140),
        ),
    ]
