# Generated by Django 3.1.7 on 2023-05-05 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20230505_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='shop_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
